name: Comment on Pull Request

on:
  push:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment on PR
        env:
          GH_ACCESSTOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          make install
          make run
