name: Comment on Pull Request

on:
  push:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment on PR
        env:
          GH_ACCESSTOKEN: ${{ secrets.GH_TOKEN }}
          pull_request_number: ${{ github.event.number }}
        run: |
          make install
          make run
