name: My Workflow

on:
  push:
  pull_request:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        env:
          GH_ACCESSTOKEN: ${{ secrets.GH_TOKEN }}
          pull_request_number: ${{ github.event.number }}
        run: |
            python3 comment.py
        
