name: Comment on Pull Request

on:
  pull_request:
    types: [opened]
  push:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment on PR
        env:
          GH_ACCESSTOKEN: ${{ secrets.GH_TOKEN}}
          REPO_NAME: ${{ github.repository }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
          MAIN_BRANCH: main

        run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          make install-commenter
          make comment-pr
